environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 23-x64
    - RUBY_VERSION: 24
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 25
    - RUBY_VERSION: 25-x64

build: off

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

test_script:
  - bundle exec rspec